version: "3.7"

services:
  fin_api_test:
    image: postgres
    container_name: fin_api_test
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api_test
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
